# Generated by Django 3.1.7 on 2021-03-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readAloudapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='notes',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriber', to='readAloudapi.profile'),
        ),
    ]
