# Generated by Django 3.1.7 on 2021-03-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readAloudapi', '0002_bookuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookUser',
            new_name='BookProfile',
        ),
    ]
